### ISSUE TITLE
Instruction on the website are outdated for Blender 2.91

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#10]
The instructions listed at the bottom of https://blenderneuron.org/download/ are incorrect for Blender 2.91 where the correct path for add-ons is: `Edit` > `Preferences` > `Add-ons`.

**Comment by JustasB** [comment]
Hi @Helveg , Thanks for pointing out the issue.

Unfortunately, Blender 2.9+ introduced many changes to its Python interface, which break the current version of BlenderNEURON. I would love for BN to work with the latest version of Blender, however and me and others have discovered that it is a non-trivial amount of work to upgrade the addon to be compatible with Blender 2.9+.

There is currently no support for Blender 2.9. 

As a workaround, you could import cell models into Blender 2.79b, save the .blend file, and open it in 2.9 to utilize the latest Blender features.

**Comment by Helveg** [comment]
Since I might be using BlenderNEURON and am in general interested in creating a Blender framework for neuroscience could we maybe plan a call with you and the some other people you think might be interested in updating and refactoring BlenderNEURON?

I'm not a big fan of the server client approach and that NEURON is pretty tightly coupled to the blender addon. I am willing to put in the work required but in the call, could we discuss:

* Updating to 2.8/2.9
* Factoring out the parts that create the morphologies and animate the cells (in the end a morphology is just an acyclic graph, it could have many more applications if you don't have to go through NEURON) (I think CurveContainer for example creates the Blender objects starting from 1 root section?)
* Factoring out the server-client so that one could just pip install neuron into blender and go for a completely headless blender scripting approach. Maybe even do some work to factor out the NEURON parts from the communication protocol (e.g. have the NEURON part of blenderNEURON calculate the 3d points of a morphology and transmitting that instead of communicating NEURON data)

**Comment by Helveg** [comment]
@JustasB tagging you, don't know if you receive notifications for closed issues ;)

**Comment by Helveg** [comment]
So this is the current situation as I understand it:

![image](https://user-images.githubusercontent.com/28923979/104563409-e6389000-5649-11eb-8589-cb8cd1621c05.png)

We have a `blenderneuron` module with the blender bootstrapping in it (could all be moved to `blenderneuron.blender` as long we import `bl_info`, `register` and `unregister`), and it starts an RCP server that asks NEURON what sections there are. Then we need to have an RCP client in NEURON that communicates the required info.

If I could be in closer contact with you I don't think it would be that much effort to restructure it to something like this:
<sub>(My main problem now is that there is no description of the architecture, no docstrings of the classes/methods and no description of the communication protocol. I'm pretty sure you could quickly fill me in on that). What's in dotted lines is me dreaming and tools that could be made by the community once we properly document the project:</sub>

![image](https://user-images.githubusercontent.com/28923979/104566835-66f98b00-564e-11eb-9126-864b553c635a.png)

In yellow are the original 2 entities refactored into 4. The key changes here being that:

* The Blender manipulator/controller thingy has a direct Python API that can be used directly.
* The Blender RCP uses the Python API
* The Blender RCP expects purely morphological and simulation data and metadata that could be provided by any simulator.
* The Blender RCP expects language agnostic configuration commands
  * We could allow for the connecting RCP client to specify "hey these are the settings you can set on me" with a configuration metadata format, that way you could keep the fancy control of NEURON from Blender, although I don't see the usecase since y'know ... you have NEURON open so just control NEURON from NEURON?

And docs docs docs, especially the Python API and RCP protocol should be crystal clear. Everything in solid lines is pretty much already there it just needs to be brought out by refactoring and documentation. Just by reshuffling code we'll win: direct scripting from Blender, scripting from any simulator instead of just NEURON (although it's probably already possible to reverse engineer an RCP client that pretends to be neuron) and offline animation (see #16)

**Comment by JustasB** [comment]
Hi again @Helveg , I appreciate the enthusiasm. Yes, these are good ideas. I can generally talk on the weekends 9AM-6PM EST and on weekdays before 9AM, during 12-1PM, and after 6PM. Let me know if one of these windows would work for you.

**Comment by Helveg** [comment]
@JustasB How about this Sunday 12PM EST? My email is robingilbert dot deschepper at unipv dot it

We can exchange skype/set up zoom there :)
