### ISSUE TITLE
BlenderNEURON in 2.91 raises warnings

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#11]
I just installed the BlenderNEURON add-on for Blender 2.91 and it raises the following warning in the GUI: `Upgrade to 2.8x required` with an exclamation mark next to it. I'm assuming the addon is outdated and won't work for Blender 2.8 or 2.9?

**Comment by JustasB** [comment]
Please see https://github.com/JustasB/BlenderNEURON/issues/10#issuecomment-759835502
