### ISSUE TITLE
BlenderNEURON broken in Blender 2.91

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#14]
The addon's `register()` function errors:

```
>>> blenderneuron.register()
register_class(...):
Warning: 'CellListWidget' doesn't contain '_UL_' with prefix & suffix
register_class(...):
Warning: 'CellGroupListWidget' doesn't contain '_UL_' with prefix & suffix
register_class(...):
Warning: 'SynapseSetListWidget' doesn't contain '_UL_' with prefix & suffix

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\robin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderneuron\__init__.py", line 82, in register
    bpy.app.handlers.scene_update_post.append(auto_start)
AttributeError: 'bpy.app.handlers' object has no attribute 'scene_update_post'
```

These will probably be only the first of many errors since the Blender Python API changed drastically in 2.8, are there any maintainers that could update this addon to 2.8 and 2.9?

**Comment by Helveg** [comment]
The `scene_update_post` handler doesn't exist anymore. I've been testing and after commenting out this auto start from the register function only the prefix/suffix warnings remain. The BlenderNEURON GUI doesn't show up anywhere though. Probably because the left sidebar doesn't seem to be there anymore in Blender 2.9?

**Comment by JustasB** [comment]
Please see: https://github.com/JustasB/BlenderNEURON/issues/10#issuecomment-759835502
