### ISSUE TITLE
Dealing with multiple Blender versions

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#17]
I think a nice way to structure the project is the following:

```
blenderneuron
  ._blender
    .addon
    .controller
    .patches
  .rpc
  .nrn
    .rpc_client
```

Since we're dealing with a peer dependency, Blender, that doesn't really seem to care for backwards compatibility, we can try to have 1 version of our package work with as many Blender versions as possible by constructing the blender addon from `._blender.addon` and then passing it through every function in `._blender.patches`, something as follows:

```python
def get_blender_version():
  try:
    return bpy.app.version_string.split(".")
  except:
    raise Exception("Oh no, they changed the API that helped us fix the changes in their API")

def patch_blender_addon():
  version = get_blender_version()
  import .addon, .controller, .patches
  for patch in sort(patches.__dict__, sorting_for_sequential_patching):
    patch(version, addon, controller)
```

The resulting `addon` module we'll inspect for a `__blender__` or `__exports__` magic dictionary whose key value pairs we import into `blenderneuron` to make the `blenderneuron` a Blender addon for the appropriate version.

This should allow every "patch function" in `._blender.patches` to modify the original `._blender.addon` and `._blender.controller` modules as it pleases based on Blender version. I think that as long as we work with atomic function such as `register_addon` which then neatly calls very precise and easy to override `register_operators`, `register_menu`, `register_ui`, ... functions we should be able to in the future apply monkey patches if they do break the API again. Same thing for the controller, whenever we use something that is blender, we should encapsulate it in a function, however tiny or silly, so that we can patch it should the API for it change, and still be able to support both versions by monkey patching like this.

The `addon` module does all the addon registering etc while the controller is the object that executes manipulations of the blender environment such as creating, deleting, moving, animating objects.

**Comment by Helveg** [comment]
Slight problem: when installing an addon into Blender, the module isn't actually loaded but they either read the lines of the module file (speedy mode) for a line that starts with `bl_info` or they use an AST and a literal eval of a target whose id is `bl_info`. In either case the module isn't actually executed so we can't dynamically create it at installation time. To succesfully register as an addon for the specific Blender version the python file itself needs to literally contain the correct values.

To run our addon (after installation) our module is actually loaded and I believe we can apply the patches.

In conclusion this means that the installer (#20) will have to obtain the blender version (probably using `blender --version` and parsing the output) and write the version into `blenderneuron/__init__.py` before asking Blender to install it.

There are 2 important and dynamic values:

* `blender`: A tuple containing the Blender version this addon was made for
* `location`: Where to display the addon, which differs from 2.7 to 2.8+

If we're unable to determine version (well, the installation is likely to fail because we can't find `blender`) we can just leave it out and a warning will appear that we need to upgrade the addon to version 2.x. If we're unable to determine version I think we best fall back to the 2.8+ location.

**Comment by JustasB** [comment]
Seems like it could get complex. 

I wonder if each BN version should target a specific Blender version (latest-ish) and users who need the addon to work in an earlier Blender version would download an earlier version of the addon. e.g. a "lock-step" strategy.

The strategy would trade management simplicity for us at the expense of the latest BN features being only available in the latest-ish version of Blender.

**Comment by Helveg** [comment]
Ah, I was brainstorming under the assumption that there was some reason you wanted to support multiple Blender versions, don't know why! If that's not required that massively simplifies things! In that case we just post a table on the README for which Blender versions each BN version supports. Sadly I don't think it'll be possible to declare this dependency in any Pythonic way, but the installer/user could pip install only versions matching the current blender version ofcourse as you suggest.
