### ISSUE TITLE
Restoring UI functionality

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#18]
In Blender 2.8/2.9 the UI does not appear (as the left side bar is gone and API's have changed). We should determine an appropriate location and display the UI there. [This StackOverflow post](https://blender.stackexchange.com/questions/57306/how-to-create-a-custom-ui) seems like a good place to get started on the 2.8+ GUI.

**Comment by Helveg** [comment]
So progress report, I found out how to add BlenderNEURON back to the UI (example of a placeholder panel):

![image](https://user-images.githubusercontent.com/28923979/104913552-0f308c00-598e-11eb-9f2c-b269d15186e3.png)

The problem is that at least on my PC it starts out collapsed and verrrrry much hidden:

![image](https://user-images.githubusercontent.com/28923979/104913684-42731b00-598e-11eb-81e0-55c0d2181496.png)

But in the community this does seem to be the most common place of adding addons :/

**Comment by JustasB** [comment]
Interesting find. I wonder how some of the popular addons deal with the collapsed panel problem. Maybe most just show how to expand the panel in their tutorials.
