### ISSUE TITLE
Is a persistent material required for the `default_color` property?

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#28]
On the `api/cell-section` branch I'm trying to get to a point where I can do:

```python
import blenderneuron as bn
import numpy as np

branch = bn.create_branch(np.array([[0, 0, 0], [10, 0, 10], [10, 10, 10]]))
cell = bn.create_cell(branch)
```

and a cell appears in Blender. For it I've moved the `CurveContainer` into the controller module and I'm trying to get it working without any `CellGroup`s as of yet.

To supply the `curve_template` and `color` I've basically replaced any `self.group` with the default values a group would have and I encountered that for the the `default` color a material is created, to then extract numeric color values. Is this material ever cleaned up or does it have further purposes? See 72a3c31ccdbc7a46f1cbb6ebdbd3eac9a9234fc3

**Comment by JustasB** [comment]
So the idea behind RootGroups is to allow the assignment of NRN  cells (root sections) to a group and then all cells that belong to a group would share the group properties like color, interaction level granularity, animation granularity, animation settings, etc... 

For the color, it comes from the group's color ramp object:
![image](https://user-images.githubusercontent.com/10732358/105043873-14481680-5a34-11eb-8744-b84fee208f0a.png)

Then the color ramp object's settings are used to create materials for child sections of the cell when they're (re-)created as Blender curve objects.

Let me know if this answers your question.

**Comment by Helveg** [comment]
Right! Thanks for the clarification. That context was lost on me, stripping off parts like it's a stolen car and never actually having used much of the UI yet :) I'll be sure to reinstate that functionality further along the road of the refactor/update.
