### ISSUE TITLE
MacOS Monterey window size issue

### ISSUE THREAD

**Issue by mgiugliano** [JustasB/BlenderNEURON#33]
On macOS Monterey 12.2.1 (21D62), Blender 2.79b is unusable for some incompatibility (i.e. Blender launches but its window is "screwed up").

The "add-ons" system changed and, due my inexperience with Blender, I am unable to understand whether it is worth investing more time.

**Comment by JustasB** [comment]
Hi @mgiugliano, Thank you for reporting the issue. I will investigate

**Comment by mgiugliano** [comment]
I would be eternally in debt with you, if you could help me getting up and running on my feet. Your work seems perfect for my need. Thank you for your time.

**Comment by JustasB** [comment]
@mgiugliano I was able to reproduce the issue on my M1 Monterey laptop -- do you happen to have an M1 laptop? 

It seems to work as expected on my older Apple laptop (Catalina, Intel CPU).

While I look more into a longer-term solution, can you try this workaround in the meantime? Once Blender starts and it looks all weird, try resizing its window and the preferences window as well.

https://user-images.githubusercontent.com/10732358/159133104-487cfa2a-3993-4445-a50a-c789ab616ed3.mov

**Comment by mgiugliano** [comment]
@JustasB Yes, that's exactly my issue. I have an Intel (not M1) MBP16 (2020). 

Your workaround worked! I feel so stupid for not having tried resizing the window. 

Do I need XQuartz working? It does not work for me in Monterey anymore (despite brew/dmg installs and several attempts). I am concerned that pip3-installing neuron on my Mac (as now recommended versus recompiling), there is no support for the "iv" X-GUI of Neuron. Without that, I am afraid I won't be able to make BlenderNeuron operating...

Any suggestion would be precious and I would love paying you a coffee.

**Comment by mgiugliano** [comment]
<img width="809" alt="Screenshot 2022-03-19 at 19 16 55" src="https://user-images.githubusercontent.com/9309421/159133558-76ae3e33-f1b9-42bb-aeca-e297342d38ad.png">
 Auch! It seems no luck with Python 3.9.10 and NEURON 8.0.

As I try to "enable" the add-on, I get this error..

**Comment by JustasB** [comment]
Hmm, I'm not able to reproduce the registration error, are you using the Blender 2.79b from this link?
https://download.blender.org/release/Blender2.79/blender-2.79b-macOS-10.6.dmg (link from the download page https://blenderneuron.org/download/)

Are also using a custom version of Python within Blender (vs the Python 3.5 that ships with Blender 2.79b)?

Looking more into the NRN 8.0 pip+GUI issue

**Comment by mgiugliano** [comment]
@JustasB Apologies! Restarting the laptop a couple of times seem to have worked. 

Now it "connects" (as soon as I launch "from blenderneuron import neuronstart" from the NEURON session). 

I managed to import the morphology! I will try to be on my own from now on.

I own you a coffee... If you have a PayPal account or BuyMeaCoffee I would definitely send you "love" (and acknowledge you on a possible future paper). :-) 
<img width="1542" alt="Screenshot 2022-03-19 at 19 29 14" src="https://user-images.githubusercontent.com/9309421/159133929-b370223b-a112-4676-9979-fd1ebeaa3161.png">

**Comment by JustasB** [comment]
@mgiugliano That's a beautiful neuron! Glad it ended up working for you.

Thank you for the coffee offer, but mentioning BlenderNEURON in your slides/figures will work for me just fine :)

If you really insist, you may make a donation here: https://donate.unhcr.org/int/en/ukraine-emergency
