### ISSUE TITLE
cannot find blenderneuron in the sidebar

### ISSUE THREAD

**Issue by miaaaaaxu** [JustasB/BlenderNEURON#34]
Hello, may I ask if this plugin is compatible with Blender version 3.2.1? I have imported and enabled the plugin in Blender, but I cannot find it in the sidebar.
<img width="660" alt="image" src="https://github.com/JustasB/BlenderNEURON/assets/133334281/3c35d0ab-d09e-4a45-8451-418600215399">
<img width="1511" alt="image" src="https://github.com/JustasB/BlenderNEURON/assets/133334281/fdfb1d20-2f20-41fa-90db-f13951b4eff0">
thank you so much!

**Comment by alistairpt** [comment]
Hi @miaaaaaxu, it looks like you're using a newer version of Blender, currently BlenderNEURON only works with Blender 2.79. Hope that helps.

**Comment by alistairpt** [comment]
Hi @miaaaaaxu, this addon is compatible with Blender 2.79, it doesn't currently work for Blender 3+.

**Comment by alistairpt** [comment]
Hi! The current release doesn't work past Blender 2.79. If you download the version from the 3+ conversion branch, it will show up in Blender 3.1-3.3 on the bar on the upper right of the 3d view, but not all functionality works as of now. Hope that helps!

**Comment by JustasB** [comment]
BlenderNEURON has been updated to be compatible with Blender 3 and 4. You can download the latest version of BlenderNEURON from here: https://blenderneuron.org/download/
