### ISSUE TITLE
Question about NeuroMorphoVis

### ISSUE THREAD

**Issue by asanin-epfl** [JustasB/BlenderNEURON#7]
Hi! There is another package https://github.com/BlueBrain/NeuroMorphoVis. Is it similar to this tool or they are supplementary to each other?

**Comment by JustasB** [comment]
NeuroMorphoVis appears to be for working with reconstructions of neurons (e.g. from slice stacks). BlenderNEURON is for working with/building computational models of neurons and networks using the NEURON simulator.

**Comment by asanin-epfl** [comment]
Thank you for clarifying
