### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by orena1** [JustasB/BlenderNEURON#9]
How do you suggest that I cite the tool? Maybe you can create zenodo link?
Thanks

**Comment by orena1** [comment]
@JustasB  ?

**Comment by JustasB** [comment]
Hi @orena1,

Thank you for using BlenderNEURON in your work.

To cite it, please cite my PhD thesis:

https://scholar.google.com/citations?user=y9mJbiYAAAAJ&hl=en&oi=ao#d=gs_md_cita-d&u=%2Fcitations%3Fview_op%3Dview_citation%26hl%3Den%26user%3Dy9mJbiYAAAAJ%26citation_for_view%3Dy9mJbiYAAAAJ%3A1yQoGdGgb4wC%26tzom%3D300

There is a more specific paper on BlenderNEURON in the works, but it won’t be available for a while.
